version: '2'
services:
  node:
    build: ./docker/node
    image: phatnguyenuit/node_dev_env
    container_name: node_development_environment
    ports:
      - 3000:3000
    volumes:
      - ./sources:/usr/workspace/sources
    restart: 'no'
    links:
      - mongo
  mongo:
    container_name: node-mongo
    image: mongo
    volumes:
      - db_volume:/data/db
      - ./backup:/data/backup
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  admin-mongo:
    container_name: admin-mongo-container
    image: 0x59/admin-mongo:latest
    ports:
      - '8082:8082'
    environment:
      - PORT=8082
      - CONN_NAME=mongo
      - DB_HOST=mongo
    links:
      - mongo
networks:
  default:
    external:
      name: bridge
